name: npm-publish
on:
  push:
    tags:
      - "v*"
jobs:
  npm-publish:
    if: github.repository == 'snolab/CapsLockX'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      # NPM 包发布
      - run: npm i -g pnpm
      - run: pnpm i
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
