on:
  push:
    tags:
      - "v*"
name: Packages Test
jobs:
  # cn:
  #   runs-on: windows-latest
  #   env:
  #     ENVIROMENT: CI_TEST
  #   steps:
  #     - run: git clone https://gitee.com/snomiao/CapslockX.git
  #     - run: .\CapsLockX\CapsLockX.exe
  gh-source:
    runs-on: windows-latest
    steps:
      - run: git clone https://github.com/snolab/CapsLockX.git
      - run: .\CapsLockX\CapsLockX.exe
        env:
          ENVIROMENT: CI_TEST
  npm-package:
    runs-on: windows-latest
    steps:
      - run: npm i -g capslockx
      #
      # dk why this can t stop, it runs 6 hours on gh actions
      # - run: npx capslockx
      # env:
      # ENVIROMENT: CI_TEST
      #
  # npx:
  #   runs-on: windows-latest
  #   env:
  #     ENVIROMENT: CI_TEST
  #   steps:
  #     - run: npx capslockx
  # choco:
  #   runs-on: windows-latest
  #   steps:
  #     - run: choco install capslockx
  #     - run: capslockx
  #       env:
  #         ENVIROMENT: CI_TEST
