# ref [自动化发布npm包及生成Github Changelog]( https://banyudu.com/posts/auto_publish_npm_and_generate_github_changelog.882513 )
on:
  push:
    tags:
      - "v*"
name: package-test
jobs:
  cn:
    runs-on: windows-latest
    steps:
      - run: git clone https://gitee.com/snomiao/CapslockX && .\CapsLockX\CapsLockX.exe --test
  gh:
    runs-on: windows-latest
    steps:
      - run: git clone https://github.com/snomiao/CapsLockX.git && .\CapsLockX\CapsLockX.exe --test
  npm:
    runs-on: windows-latest
    steps:
      - run: npm i -g capslockx && capslockx --test
  npx:
    runs-on: windows-latest
    steps:
      - run: npx capslockx --test
  choco:
    runs-on: windows-latest
    steps:
      - run: choco install capslockx && capslockx --test
