# ref [自动化发布npm包及生成Github Changelog]( https://banyudu.com/posts/auto_publish_npm_and_generate_github_changelog.882513 )
on:
  push:
    branches:
      - "master"
    tags:
      - "v*"
name: Publish
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 10
          registry-url: https://registry.npmjs.org/
      # NPM 源码发布
      - run: npm i
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      # Github 源码发布
      - run: npm i -g github-release-from-changelog
      - run: github-release-from-changelog
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  package:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # 获取版本号 [continuous integration - Get the current pushed tag in Github Actions - Stack Overflow]( https://stackoverflow.com/questions/58177786/get-the-current-pushed-tag-in-github-actions )
      - name: Get Version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      # 打包
      - uses: montudor/action-zip@v0.1.1
        with:
          args: zip -r CapsLockX${{ env.RELEASE_VERSION }}.zip Core Data Docs Modules Tools CapsLockX*.* LICENCE README.md SECURITY.md "启动 CapsLockX.lnk"
      # 上传
      - uses: actions/upload-artifact@v2
        with:
          path: CapsLockX${{ env.RELEASE_VERSION }}.zip
          name: CapsLockX${{ env.RELEASE_VERSION }}.zip
      # 压缩包和 Docs 一起同步到 gh-pages
      - run: mv CapsLockX${{ env.RELEASE_VERSION }}.zip Docs/CapsLockX${{ env.RELEASE_VERSION }}.zip
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./Docs
  # chocolatey:
  #   needs: release
  #   runs-on: windows-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #     # Cocolatey 发布
  #     - name: Choco help
  #       uses: crazy-max/ghaction-chocolatey@v1
  #       with:
  #         args: pack
