# ref [自动化发布npm包及生成Github Changelog]( https://banyudu.com/posts/auto_publish_npm_and_generate_github_changelog.882513 )
on:
    push:
        tags:
            - "v*"
name: github-release-into-gh-pages
jobs:
    github-release:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: 14
                  registry-url: https://npm.pkg.github.com
            # Github release with changelog
            - run: npm i -g github-release-from-changelog
            - run: github-release-from-changelog
              env:
                  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
            # pack
            - run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
            - run: mkdir -p ./CapsLockX-${{ env.RELEASE_VERSION }}
            - run: cp -r docs Core Data Modules Tools *.exe *.ahk *.txt *.md ./CapsLockX-${{ env.RELEASE_VERSION }}
            - run: zip -r CapsLockX-${{ env.RELEASE_VERSION }}.zip ./CapsLockX-${{ env.RELEASE_VERSION }} -UN=UTF8
            # upload
            - uses: svenstaro/upload-release-action@v2
              with:
                  repo_token: ${{ secrets.GITHUB_TOKEN }}
                  file: CapsLockX-${{ env.RELEASE_VERSION }}.zip
                  tag: ${{ github.ref }}
            # push to gh pages
            - run: cp CapsLockX-${{ env.RELEASE_VERSION }}.zip docs/CapsLockX-${{ env.RELEASE_VERSION }}.zip
            - run: cp CapsLockX-${{ env.RELEASE_VERSION }}.zip docs/CapsLockX-latest.zip
            - run: cp CHANGELOG.md docs/CHANGELOG.md
            - run: cp Core/version.txt docs/version.txt
            - uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./docs
                  enable_jekyll: true
