# ref [自动化发布npm包及生成Github Changelog]( https://banyudu.com/posts/auto_publish_npm_and_generate_github_changelog.882513 )
on:
  push:
    branches:
      - master
name: debug
jobs:
  chocolatey-publish:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      # 打包 校验
      - run: choco install zip checksum
      # - uses: actions/cache@v1
      #   id: env_cache
      #   with:
      #     path: # TODO
      #     key: ${{ runner.os }}-# TODO
      - run: |
          zip -r CapsLockX.zip Core Data docs Modules Tools CapsLockX* LICENSE *.md "启动 CapsLockX.lnk"
          checksum -t sha256 -f CapsLockX.zip > CapsLockX.sha256
          cp -force LICENSE           tools/choco/tools/LICENSE.txt
          cp -force CapsLockX.zip     tools/choco/tools/
          cp -force CapsLockX.sha256  tools/choco/tools/
          choco pack Tools/choco/CapsLockX.nuspec
      # 测试
      - run: |
          cinst CapsLockX -s .
      # 发布
      - run: |
          choco apikey --key ${{ secrets.CHOCOLATEY_APIKEY }} --source https://push.chocolatey.org/
      - run: |
          choco push
